### ISSUE TITLE
Panda error while creating Online test data

### ISSUE THREAD

**Issue by hxue3** [facebookresearch/CodeGen#46]
I am following the instructions for Transcoder-ST. I got this error

########## Creating Tests ##########
Running on the remaining 0 among 1 files
/opt/conda/envs/codeGen_env/lib/python3.6/site-packages/submitit/core/core.py:628: UserWarning: Received an empty job array
  warnings.warn("Received an empty job array")
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "codegen_sources/test_generation/create_tests.py", line 279, in <module>
    output_selected_tests_summary(out_folder)
  File "codegen_sources/test_generation/create_tests.py", line 189, in output_selected_tests_summary
    csv = pd.read_csv(csv_file)
  File "/opt/conda/envs/codeGen_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/envs/codeGen_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/conda/envs/codeGen_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/opt/conda/envs/codeGen_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/conda/envs/codeGen_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by brozi** [comment]
Hi, 
So it's failing when trying to consolidate the test summaries created by evosuite. You could rerun the test creation command with --rerun=True (or delete the `tests` directory in your output folder) and rerun this after checking that there are some files matchin the pattern `java.000*.sa.tok` in the JAVA_FUNC_DATASET folder you passed to the script.
